# SwiftLint Configuration for StillView - Simple Image Viewer

# Paths to include during linting
included:
  - StillView - Simple Image Viewer

# Paths to exclude during linting
excluded:
  - StillView - Simple Image Viewer Tests
  - StillView - Simple Image Viewer.xcodeproj
  - .build

# Rules to disable
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for now
  - todo # Allow TODO comments

# Rules to enable
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - strong_iboutlet
  - closure_spacing
  - operator_usage_whitespace

# Configure rules
line_length:
  warning: 120
  error: 150
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length: 1
  max_length: 60

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    match_kinds: 
      - identifier
    message: "Use os.log instead of print statements"
    severity: warning