name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build
      run: |
        xcodebuild -project "StillView - Simple Image Viewer.xcodeproj" \
                   -scheme "StillView - Simple Image Viewer" \
                   -configuration Debug \
                   -destination "platform=macOS" \
                   build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO
    
    - name: Run Tests
      run: |
        xcodebuild test \
          -project "StillView - Simple Image Viewer.xcodeproj" \
          -scheme "StillView - Simple Image Viewer" \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
